package com.quyiyuan.exportDataToExcel;

import java.awt.Toolkit;

import javax.swing.JOptionPane;

import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author __USER__
 */
public class Frame extends javax.swing.JFrame {

	private static final long serialVersionUID = -8648374168108598593L;

	/** Creates new form Frame */
	public Frame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		title = new javax.swing.JLabel();
		exportButton = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		userName = new javax.swing.JTextField();
		department = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		amount = new javax.swing.JTextField();
		timeLine = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txtAddress = new javax.swing.JTextField();
		excelAddress = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		title.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		title.setText("\u52a0\u73ed\u8868\u5bfc\u51fa\u5de5\u5177");

		exportButton.setText("\u6267\u884c\u5bfc\u51fa");
		exportButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				exportButtonMouseClicked(evt);
			}
		});

		jLabel2.setText("\u7528\u6237\u59d3\u540d\uff1a");

		jLabel3.setText("\u6240\u5c5e\u90e8\u95e8\uff1a");

		jLabel4.setText("\u8d77\u7b97\u65f6\u95f4\uff1a");

		jLabel5.setText("\u8865\u52a9\u91d1\u989d\uff1a");

		jLabel1.setText("\u6587\u4ef6\u8def\u5f84\uff1a");

		jLabel6.setText("\u5bfc\u51fa\u8def\u5f84\uff1a");

		jLabel7.setText("\u5982\u6709bug\uff0c\u8bf7\u8054\u7cfb\u4f5c\u8005\uff1a\u51af\u4e7e\u5b81");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2)
												.addComponent(jLabel4)
												.addComponent(jLabel5)
												.addComponent(jLabel1)
												.addComponent(jLabel6)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														userName,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														163, Short.MAX_VALUE)
												.addComponent(
														excelAddress,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														163, Short.MAX_VALUE)
												.addComponent(
														txtAddress,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														163, Short.MAX_VALUE)
												.addComponent(
														amount,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														163, Short.MAX_VALUE)
												.addComponent(
														timeLine,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														163, Short.MAX_VALUE)
												.addComponent(
														department,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														163, Short.MAX_VALUE))
								.addGap(39, 39, 39))
				.addGroup(
						layout.createSequentialGroup().addComponent(jLabel7)
								.addContainerGap(139, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(120, Short.MAX_VALUE)
								.addComponent(exportButton)
								.addGap(105, 105, 105))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(113, Short.MAX_VALUE)
								.addComponent(title).addGap(95, 95, 95)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(title)
								.addGap(19, 19, 19)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														userName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														department,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														timeLine,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														amount,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtAddress,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														excelAddress,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(exportButton)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										22, Short.MAX_VALUE)
								.addComponent(jLabel7)));

		title.getAccessibleContext().setAccessibleName("title");

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void exportButtonMouseClicked(java.awt.event.MouseEvent evt) {
		this.exportButton.setEnabled(false);
		String usernameNew = userName.getText();
		String departmentNew = department.getText();
		String amountNew = amount.getText();
		String timeLineNew = timeLine.getText();
		String txtAddressNew = txtAddress.getText();
		if (StringUtils.isBlank(txtAddressNew)) {
			JOptionPane.showMessageDialog(this, "输入文件路径为空", "提示 ",
					JOptionPane.NO_OPTION);
			this.exportButton.setEnabled(true);
			return;
		}
		String excelAddressNew = excelAddress.getText();
		Config.saveConfig(usernameNew, departmentNew, amountNew, timeLineNew,
				txtAddressNew, excelAddressNew);
		String result = ExportDataToExcel.execute();
		JOptionPane.showMessageDialog(this, result, "提示 ",
				JOptionPane.NO_OPTION);
		this.exportButton.setEnabled(true);
	}

	public void init() {
		this.setResizable(false);
		this.setTitle("加班表导出工具");
		this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2
				- this.getWidth() / 2, Toolkit.getDefaultToolkit()
				.getScreenSize().height / 2 - this.getHeight() / 2 - 100);
		userName.setText(Config.USERNAME);
		department.setText(Config.DEPARTMENT);
		amount.setText(String.valueOf(Config.AMOUNT));
		timeLine.setText(Config.TIME_LINE);
		txtAddress.setText(Config.FILE_PATH);
		excelAddress.setText(Config.EXCEL_PATH);
	}


	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField amount;
	private javax.swing.JTextField department;
	private javax.swing.JTextField excelAddress;
	private javax.swing.JButton exportButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField timeLine;
	private javax.swing.JLabel title;
	private javax.swing.JTextField txtAddress;
	private javax.swing.JTextField userName;
	// End of variables declaration//GEN-END:variables

}